Praca/mysite/medapp/urls.py
from django.urls import path
from . import views
from django.urls import path
from .views import  ProductCreateView, ProductUpdateView, ProductDeleteView 

app_name = 'medapp'

urlpatterns = [
    path('product/<int:pk>/', views.product_detail, name='product-detail'),
    path('profile/<int:pk>/', views.profile_detail, name='profile-detail'),
    path('product/new/', ProductCreateView.as_view(), name='product-create'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product-update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product-delete'),
    path('products/', views.product_list, name='product_list'),
    path('products/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('account/edit', views.edit , name='edit'),
    path('contact', views.contact , name='contact'),
]

Praca/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from medapp import views as medapp_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('my_products/', medapp_views.my_products, name='my_products'),
    path('orders/', medapp_views.order_list, name='orders'),
    path('', include('medapp.urls', namespace='medapp')),
    path('', medapp_views.home, name='home'),
    path('register/', medapp_views.register, name='register'),
    path('account/', medapp_views.account, name='account' ),
    path('login/', auth_views.LoginView.as_view(template_name='medapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='medapp/logout.html'), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='medapp/password_change.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='medapp/password_change_done.html'), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='medapp/password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='medapp/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='medapp/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='medapp/password_reset_complete.html'), name='password_reset_complete'),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Praca/mysite/medapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Contact, Profile, Order


class UserRegisterForm(forms.ModelForm):
    """
    A form for user registration. Includes email, username, and password fields.
    It verifies that the provided passwords match and ensures the email is unique.
    """
    password = forms.CharField(label='Hasło', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Powtórz hasło', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True

    class Meta:
        model = User
        fields = ('email', 'username',)

    def clean_password2(self): 
        """
        Validate that both password fields match.
        Raises a validation error if they do not.
        """
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Hasła nie są identyczne')
        return cd['password2']    
    
    def clean_email(self): 
        """
        Check if the provided email is already in use.
        Raises a validation error if the email is found in the database.
        """
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email już istnieje")
        return email


class UserEditForm(forms.ModelForm):
    """
    Form for editing a User instance.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True

    class Meta:
        model = User
        fields = ('username', 'email')
        labels = {
            'username': 'Nazwa użytkownika',
            'email': 'Adres e-mail'
        }


class ProfileEditForm(forms.ModelForm):
    """
    Form for editing a Profile instance.
    """
    class Meta:
        model = Profile
        fields = ('description', 'image')
        labels ={
            'description': 'Opis profilu',
            'image': 'Zdjęcie profilowe'
        }

class ContactForm(forms.ModelForm):
    """
    Form for submitting contact information.
    """
    class Meta:
        model = Contact
        fields = '__all__'
        labels = {
            'email_guest': 'Adres e-mail',
            'topic': 'Temat',
            'message_text': ' Twoja wiadomość'
        }

class OrderFrom(forms.ModelForm):
    """
    Form for creating or editing an Order instance.
    """
    class Meta:
        model = Order
        fields = ('quantity', 'days', 'name1','name2','phone_number','home_number','apartment','postcode', 'city_name')
        labels ={
            'quantity':'Ilość', 
            'days': 'Ilość dni', 
            'name1': 'Imię',
            'name2': 'Nazwisko',
            'phone_number': 'Numer telefonu',
            'home_number': 'Adres',
            'apartment': 'Numer mieszkania',
            'postcode': 'Kod pocztowy', 
            'city_name': 'Miasto'
        }

Praca/mysite/medapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from .forms import *
from django.contrib.auth.decorators import login_required
from .models import *
from django.views.generic import CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def register(request):
    """
    Handles the user registration process.

    If the request method is POST, it validates the submitted form data. 
    If the form is valid, a new user is created. 

    Args:
        request: The HTTP request object.

    Returns:
        A rendered response with the registration form or a redirect to the login page 
        if the registration is successful.
    """
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            messages.success(request, f'Stworzono konto!')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'medapp/register.html', {'form': form})

def contact(request):
    """
    Handles the contact form submission.

    If the request method is POST, it validates the submitted form data. 
    If the form is valid, the contact message is saved.

    Args:
        request: The HTTP request object.

    Returns:
        A rendered response with the contact form or a redirect to the contact page 
        if the form submission is successful.
    """
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            messages.success(request, 'Wysłano widomość!')
            return redirect('medapp:contact')
        else:
            messages.error(request, 'Błąd!')
    else:
        contact_form = ContactForm()
    return render(request,'medapp/contact.html',{'contact_form': contact_form})
    

def home(request):
    """
    Renders the home page of the application.

    Args:
        request: The HTTP request object.

    Returns:
        A rendered response with the 'home' page template and the context containing 
        the title of the page.
    """
    return render(request, 'medapp/home.html', {'title': 'Strona Główna'})


def categories(request):
    """
    Retrieves all categories from the database.

    Args:
        request: The HTTP request object.

    Returns:
        A dictionary containing all the categories in the 'categories' key.
    """
    categories = Category.objects.all()
    return {'categories': categories}


def product_list(request, category_slug=None):
    """
    Displays a list of available products, optionally filtered by category.

    Args:
        request: The HTTP request object.
        category_slug: An optional slug for filtering products by category.

    Returns:
        A rendered response with the 'product list' template, including the 
        filtered products, categories, and pagination information.
    """
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    p = Paginator(products, 12)
    page_number = request.GET.get('page', 1)

    try:
        page_obj = p.get_page(page_number)
    except PageNotAnInteger:
        page_obj = p.page(1)
    except EmptyPage:
        page_obj = p.page(p.num_pages)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

        p = Paginator(products, 12)
        page_number = request.GET.get('page', 1)

        try:
            page_obj = p.get_page(page_number)
        except PageNotAnInteger:
            page_obj = p.page(1)
        except EmptyPage:
            page_obj = p.page(p.num_pages)
        
    return render(request, 'medapp/products/list.html',{'category': category, 'categories':categories,'products':products, 'page_obj':page_obj})


@login_required
def account(request):
    """
    Renders the user's profile page, only for authenticated users.

    Args:
        request: The HTTP request object.

    Returns:
        A rendered response with the 'account' page template.
    """
    return render(request, 'medapp/account.html', {'title': 'Profil'})      


@login_required
def my_products(request):
    """
    Displays the list of products created by the currently logged-in user.

    Args:
        request: The HTTP request object.

    Returns:
        A rendered response with the 'my_products' page template, displaying 
        the user's products.
    """
    products = Product.objects.filter(author = request.user.id)
    return render(request, 'medapp/my_products.html',{'products':products})


@login_required
def order_list(request):
    """
    Displays the list of orders for products created by the currently logged-in user,
    only for authenticated users.

    Args:
        request: The HTTP request object.

    Returns:
        A rendered response with the 'orders' page template, displaying 
        the user's orders.
    """
    orders = Order.objects.filter(product__author = request.user.id)
    return render(request, 'medapp/orders.html',{'orders':orders})


@login_required
def product_detail(request, pk):
    """
    Displays the details of a specific product and handles the order form submission,
    only for authenticated users.

    Args:
        request: The HTTP request object.
        pk: The primary key of the product to be displayed.

    Returns:
        A rendered response with the 'product_detail' page template, 
        displaying the product details and order form.
    """
    product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        order_form = OrderFrom(data=request.POST)
        if order_form.is_valid():
            cd = order_form.cleaned_data
            new_order = order_form.save(commit=False)
            new_order.user = request.user
            new_order.product = product
            order_form.save()
            messages.success(request, 'Zamówienie złożone pomyślnie!')
            return redirect('medapp:product_list')
        else:
            messages.error(request, 'Błąd!')
    else:
        order_form = OrderFrom(instance=request.user)
    return render(request, 'medapp/product_detail.html', {'product': product, 'order_form': order_form})


class ProductCreateView(LoginRequiredMixin, CreateView):
    """
    View for creating a new product.

    Inherits from:
        LoginRequiredMixin: Ensures that only authenticated users can access this view.
        CreateView: Provides the functionality to create a new instance of a model.

    Attributes:
        model: The model associated with the form (Product).
        fields: The fields to be included in the form for creating a product.

    Methods:
        form_valid(form): Customizes the form submission by assigning the current user 
                          as the product's author before saving the product.
    
    Args:
        request: The HTTP request object.
    """
    model = Product
    fields = ['category', 'name', 'image', 'description', 'price','available' ,'city', 'quantity']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    View for updating an existing product.

    Inherits from:
        LoginRequiredMixin: Ensures that only authenticated users can access this view.
        UserPassesTestMixin: Ensures that only the author of the product can update it.
        UpdateView: Provides functionality to update an existing instance of a model.

    Attributes:
        model: The model associated with the form (Product).
        template_name: The template to be used for rendering the product update form.
        fields: The fields to be included in the form for updating a product.

    Methods:
        form_valid(form): Customizes the form submission by assigning the current user 
                          as the product's author before saving the updated product.
        test_func(): Checks if the current user is the author of the product and 
                     grants permission to update it.

    Args:
        request: The HTTP request object.
    """
    model = Product
    template_name ='medapp/product_update.html'
    fields = ['category', 'name', 'image', 'description', 'price' ,'available', 'city', 'quantity']
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        product = self.get_object()
        if self.request.user == product.author:
            return True
        else:
            return False


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    View for deleting an existing product.

    Inherits from:
        LoginRequiredMixin: Ensures that only authenticated users can access this view.
        UserPassesTestMixin: Ensures that only the author of the product can delete it.
        DeleteView: Provides functionality to delete an existing instance of a model.

    Attributes:
        model: The model associated with the deletion (Product).
        success_url: The URL to redirect to after successfully deleting the product.

    Methods:
        test_func(): Checks if the current user is the author of the product and 
                     grants permission to delete it.

    Args:
        request: The HTTP request object.
    """
    model = Product
    success_url ='/products/'

    def test_func(self):
        product = self.get_object()

Praca/mysite/medapp/templates/medapp/account_edit.html
{% extends "medapp/base.html" %}
{% load crispy_forms_tags %}


{% block title %}Edytuj swój profil{% endblock title %}

{% block content %}

  <form class="form-signin" style="max-width: 800px; height: 800px;" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="border-bottom">
      <h2 class="pt-3">Edytuj swój profil</h2>
    </div>
    {{ user_form|crispy }}
    {{ profile_form|crispy}}
    <button  class="btn btn-lg btn-primary btn-block" type="submit">Zapisz zmiany</button>
  </form>
  
{% endblock %}

Praca/mysite/medapp/templates/medapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>MedApp</title>
    {% endif %}

    <link href="{% static "css/style.css" %}" rel="stylesheet">

  </head>
  <body class="bg-light" >

    <!-- Navbar -->

    <nav class="navbar navbar-expand-md bg-white navbar-light py-3">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Medapp</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item pr-2">
              <a class="nav-link home-item" href="{% url 'home' %}">HOME</a>
            </li>
            <li class="nav-item pr-2">
              <a class="nav-link" href="#">O NAS</a>
            </li>
            <li class="nav-item pr-2">
              <a class="nav-link" href="{% url 'medapp:contact' %}">KONTAKT</a>
            </li>

            <!-- Dropdown -->
            
            <li class="nav-item pr-2 dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">PRODUKTY</a>
              <ul class="dropdown-menu" aria-labelledby="dropdown01">
                <li>
                  <a class="dropdown-item" href="{% url "medapp:product_list" %}">Wszystkie</a>
                </li>
                {% for c in categories %}
                  <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                  </li>
                {% endfor %}
              </ul>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item pr-2">
              <a class="nav-link" href="{% url 'account' %}">PROFIL</a>
            </li>
            <li class="nav-item pr-2">
              <a class="nav-link" href="{% url 'logout' %}">WYLOGUJ</a>
            </li>
            {% else %}
            <li class="nav-item pr-2">
              <a class="nav-link" href="{% url 'register' %}">REJESTRACJA</a>
            </li>
            <li class="nav-item pr-2">
              <a class="nav-link" href="{% url 'login' %}">ZALOGUJ</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>


    <div class="container">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    </div>
    {% block content %}
    {% endblock %}


    <!-- Toolbar -->

    <div class="container-fluid">
      <footer class="pt-4 my-md-5 pt-md-5 border-top ">
        <div class="row justify-content-md-center">
          <div class="col col-md-3">
            <h5>Medapp</h5>
            <ul class="list-unstyled text-small">
              <li class="pb-1"><h6><a class="text-muted" href="{% url 'home' %}">Home</a></h6></li>
              <li class="pb-1"><h6><a class="text-muted" href="#">O nas</a></h6></li>
              <li class="pb-1"><h6><a class="text-muted" href="{% url "medapp:product_list" %}">Produkty</a></h6></li>
              <li class="pb-1"><h6><a class="text-muted" href="{% url 'account' %}">Profil</a></h6></li>
              <li class="pb-1"><h6><a class="text-muted" href="{% url 'medapp:contact' %}">Kontakt</a></h6></li>
            </ul>
          </div>
          <div class="col col-md-3">
            <h5>Dane kontaktowe</h5>
            <ul class="list-unstyled ">
              <li class="pb-1"><h6 class="text-muted">Skontaktuj się z nami, a z przyjemnością odpowiemy na Twoje pytania.</h6></li>
              <li><a class="text-muted">Numer telefonu:</a></li>
              <li><a class="text-muted"><img src="{% static "img/telephone.svg" %}" alt="Ikona telefonu" width="25" height="25"> +48 567 985 565</a></li>
              <li><a class="text-muted">Adres email:</a></li>
              <li><a class="text-muted"><img src="{% static "img/envelope.svg" %}" alt="Ikona email" width="25" height="25"> obsługa.strony@gmail.pl</a></li>
            </ul>
          </div>
          <div class="col col-md-2">
            <p class="text-center">
              <a href="#"><img src="{% static "img/arrow-up-circle.svg" %}" alt="Powrót na górę" width="50" height="50"></a>
            </p>
          </div>
        </div>
      </footer>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

Praca/mysite/medapp/templates/medapp/contact.html
{% extends "medapp/base.html" %}
{% load crispy_forms_tags %}


{% block title %}Formularz kontaktowy{% endblock %}

{% block content %}
  <form class="form-signin border-box" style="max-width: 800px; height: 650px;" method="post">
    {% csrf_token %}
    <div class="border-bottom">
      <h2 class="pt-3">Skontaktuj się z nami!</h2>
    </div>
    {{ contact_form|crispy}}
    {% csrf_token %}
    <button  class="btn btn-lg btn-primary btn-block" type="submit">Wyślij wiadomość</button>
  </form>

{% endblock %}

Praca/mysite/medapp/templates/medapp/home.html
{% extends "medapp/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="jumbotron" style=" height: 800px; background-image: url('/static/img/home.jpg');">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
      <strong><h1 class="display-3 font-weight-normal text-white pt-5">Medapp</h1></strong>
      <h3 class=" font-weight-normal text-white pt-2 pb-2">Pomóż sobie już dzisiaj. Skorzystaj z oferty wynajmu sprzętu medycznego już teraz.</h3>
      <a class="btn btn-outline-secondary text-white " href="#">Dowiedz się więcej</a>
    </div>
</div>
<div class="container-fluid">
    <!---<h1>Strona Główna</h1>
    <a href="{% url 'medapp:contact' %}">Skontktuj się z nami</a>-->
</div> 
    
{% endblock content %}

Praca/mysite/medapp/templates/medapp/login.html
{% extends "medapp/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form class="form-signin pt-5" method="POST">
        {% csrf_token %}
        <div class="text-center pt-5 mb-4">
            <h2 class="pt-5">Logowanie</h2>
        </div>
        {{ form|crispy }}
        <button  class="btn btn-lg btn-primary btn-block" type="submit">Zaloguj się!</button>
        <div class="pt-3">
            Potrzebujesz założyć konto? <a href="{% url 'register' %}">Zarejestruj się</a>
        </div>
        <div>
            Zapomniałeś hasła? <a href="{% url 'password_reset' %}">Ustaw nowe hasło</a>
        </div>
    </form>
   
{% endblock content %}

Praca/mysite/medapp/templates/medapp/my_products.html
{% extends "medapp/base.html" %}
{% load static %}


{% block content %}

<div class="container-fluid">  
  <h2 class="pb-5 pt-5">Lista dodanych produktów</h2>
    <div class="album py-1 ">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-1">
        {% for product in products %}
        <div class="col pb-4">
            <div class="card shadow-sm " style="width: 17rem; margin: auto;">
              <a href="{{ product.get_absolute_url }}">
                <img class="img-fluid" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
              </a>
              <div class="card-body text-center">
                <h5 class="card-title"><a class="text-muted" href="{{ product.get_absolute_url }}">{{ product.name }}</a></h5>
                <h6>{{ product.price }}zł/dzień</h6>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group mx-auto">
                    <button type="button" class="btn btn-sm btn-outline-secondary ">Zamów teraz</button>
                  </div>
                </div>
              </div>
            </div>  
        </div>
        {% endfor %}
      </div>          
    </div>  
</div>      
{% endblock %}

Praca/mysite/medapp/templates/medapp/password_change_done.html
{% extends "medapp/base.html" %}

{% block content %}
<div class="container-fluid pt-5" id="logout__screen">
    <div class="starter-template pt-5"> 
        <h1 class="pt-5">Hasło zostało zmienione</h1>
        <p>Zmiana hasła zakończyła się powodzeniem</p>
    </div>
</div>
{% endblock content %}

Praca/mysite/medapp/templates/medapp/password_reset_email.html
Otrzymaliśmy żadanie wyzerowania hasła dla użytkownika używającego adresu e-mail 
{{ email }}. Kliknij poniższe łącze:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
Twoja nazwa użytkownika: {{ user.get_username }}

Praca/mysite/medapp/templates/medapp/product_detail.html
{% extends "medapp/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
  {{ object.name }}
{% endblock %}

{% block content %}
<div class="container">
  <div class="row pt-3">
    <div class="col">
      <img id="detail-img" style="width: 40rem;" src="{% if product.image %}{{ product.image.url }}{% else %}
      {% static 'img/no_image.png' %}{% endif %}">
    </div>

    <div class="col">
      <div class="pb-5 pt-3">
        <h1 class="mb-0 pb-3">{{ product.name }}</h1>
        <h5>
          {% if product.author == user %}
              Wynajmujący:
            <a class="text-muted" href="{% url 'account' %}">
              {{ product.author }}
            </a>
          {% else %}
            Wynajmujący:
            <a class="text-muted" href="{{ product.author.profile.get_absolute_url }}">
              {{ product.author }}
            </a>
          {% endif %}
        </h5>
        <h5>
            Kategoria produktu:
          <a class="text-muted" href="{{ product.category.get_absolute_url }}">
            {{ product.category }}
          </a>
        </h5>
        <h5 class="pb-5">
          Dostępna ilość: {{ product.quantity }}
      </h5>
      </div>
      <div class="border">
          <div class="col border-bottom">
              <div class="row p-3">
                  <div class="col-6"><h5>Kwota za dzień:</h5> </div>
                  <div class="col-6 text-end"><span class="h4 fw-bold">{{ product.price }} zł</span></div>
              </div>
          </div>
          <div class="col border-bottom">
              <div class="row p-3">
                   <!-- Button trigger modal -->
                  <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#exampleModalCenter">
                    Złóż zamówienie
                  </button>
              </div>
          </div>
          {% if product.author == user %}
          <div class="col">
            <div class="row p-3">   
                <div class="col " style="padding: 0 5px 0 0 ;">
                  <a class="btn btn-secondary btn-block" href="{% url 'medapp:product-update' product.id %}">Aktualizuj</a>
                </div>
                <div class="col" style="padding: 0 0 0 5px;">
                  <a class="btn btn-danger btn-block" href="{% url 'medapp:product-delete' product.id %}">Usuń</a>
                </div>
            </div>
          </div>
          {% endif %}
      </div>
    </div>

  </div>
</div>
<div class="container-fluid">
  <div class=" my-md-5 border-top">
  </div>
</div>
<div class="container">
    <h4>{{ product.name }}</h4>
    {{ product.description|linebreaks }}
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Formularz zamówienia</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST">
          {% csrf_token %}
          {{ order_form|crispy }}
          <button class="btn btn-outline-info" type="submit">Złóż zamówienie!</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}